import { Client, handle_file } from "@gradio/client";
import { FREE_RUNNERS } from "./free-runners";

type FileLike = File | Blob | string;
type Inputs = Record<string, unknown> | unknown[];
type EndpointParam = { label?: string; parameter_name?: string; component?: string; type?: string; default?: unknown; optional?: boolean; parameter_has_default?: boolean };
type EndpointInfo = { parameters?: EndpointParam[]; returns?: unknown[]; description?: string; fn?: string };
type ApiInfo = { named_endpoints?: Record<string, EndpointInfo>; unnamed_endpoints?: Record<string, EndpointInfo> };
type ClientLike = { predict: (name: string, data?: unknown) => Promise<unknown>; submit: (name: string, data?: unknown) => AsyncIterable<{ type?: string; data?: unknown; message?: string }>; view_api?: () => Promise<ApiInfo> };
type LogicalId = keyof typeof FREE_SPACE_IDS;
type Health = { failures: number; successes: number; nextRetryAt: number; lastError?: string };

const CONNECT_TIMEOUT = 30_000;
const API_TIMEOUT = 30_000;
const JOB_TIMEOUT = 12 * 60_000;
const CACHE_TTL = 30_000;
const RETRY_BASE = 5_000;
const RETRY_MAX = 90_000;
const MAX_ATTEMPTS = 2;

export const FREE_SPACE_IDS = { speechToText: "speechToText", music: "music", image: "image", video: "video", voiceClone: "voiceClone", voicePreset: "voicePreset", voiceSwap: "voiceSwap", vocalSeparation: "vocalSeparation" } as const;
const CAPABILITIES: Record<LogicalId, string[]> = {
  speechToText: ["speech-to-text", "realtime-asr", "transcription"], music: ["music", "song", "lyrics-to-music", "audio-to-audio"], image: ["image", "artwork", "cover", "image-edit"], video: ["video", "image-to-video", "text-to-video", "audio-to-video", "music-video"], voiceClone: ["voice-clone", "tts"], voicePreset: ["tts", "multilingual-tts"], voiceSwap: ["voice-swap", "singing-voice-conversion", "ai-cover"], vocalSeparation: ["vocal-separation", "vocal-isolation", "stems"],
};
const clients = new Map<string, Promise<ClientLike>>();
const apiCache = new Map<string, { info: ApiInfo; expires: number }>();
const health = new Map<string, Health>();

function withTimeout<T>(promise: Promise<T>, ms: number, message: string) { let timer: ReturnType<typeof setTimeout> | undefined; return Promise.race([promise, new Promise<T>((_, reject) => { timer = setTimeout(() => reject(new Error(message)), ms); })]).finally(() => timer && clearTimeout(timer)); }
function normal(value: unknown) { return String(value ?? "").toLowerCase().replace(/[^a-z0-9]/g, ""); }
function spaceNames(logical: LogicalId) { const wanted = new Set(CAPABILITIES[logical]); return FREE_RUNNERS.filter((r) => r.kind === "public" && r.capabilities.some((c) => wanted.has(c))).map((r) => ({ id: r.url.replace("https://huggingface.co/spaces/", "").replace(/\/$/, ""), priority: r.priority })).sort((a, b) => b.priority - a.priority); }
function state(logical: LogicalId, space: string) { const key = `${logical}:${space}`; const current = health.get(key); if (current) return current; const fresh: Health = { failures: 0, successes: 0, nextRetryAt: 0 }; health.set(key, fresh); return fresh; }
function success(logical: LogicalId, space: string) { const s = state(logical, space); s.successes++; s.failures = 0; s.nextRetryAt = 0; s.lastError = undefined; }
function failure(logical: LogicalId, space: string, error: unknown) { const s = state(logical, space); s.failures++; s.lastError = error instanceof Error ? error.message : String(error); s.nextRetryAt = Date.now() + Math.min(RETRY_MAX, RETRY_BASE * 2 ** Math.min(s.failures - 1, 4)); clients.delete(space); apiCache.delete(space); }
function endpoints(info: ApiInfo) { return { ...(info.named_endpoints ?? {}), ...(info.unnamed_endpoints ?? {}) }; }

export function connectFreeSpace(space: string, onStatus?: (message: string) => void) { let promise = clients.get(space); if (!promise) { promise = Client.connect(space, { events: ["data", "status"], status_callback: (status: unknown) => { const message = typeof status === "string" ? status : (status as { message?: string })?.message; if (message) onStatus?.(message); } }) as unknown as Promise<ClientLike>; promise.catch(() => clients.delete(space)); clients.set(space, promise); } return promise; }
export function freeFile(file: FileLike) { return file; }

function inputFor(name: string, inputs: Record<string, unknown>) {
  const n = normal(name);
  const exact = Object.entries(inputs).find(([key]) => normal(key) === n)?.[1]; if (exact !== undefined) return exact;
  const aliases: Record<string, string[]> = {
    audio: ["audio", "inputaudio", "sourceaudio", "sourceaudiopath", "audiofile"], image: ["image", "inputimage", "sourceimage", "imagefile", "input"], video: ["video", "inputvideo", "sourcevideo", "videofile"], prompt: ["prompt", "description", "textprompt", "styleprompt", "text", "captions", "caption"], text: ["text", "prompt", "targettext", "lyrics", "lrc", "captions", "caption"], lyrics: ["lyrics", "lrc", "lyric", "text"], lrc: ["lrc", "lyrics", "lyric", "text"], refaudio: ["refaudio", "referenceaudio", "targetaudio", "targetaudiopath"], referenceaudio: ["referenceaudio", "refaudio", "targetaudio", "targetaudiopath"], sourceaudio: ["sourceaudio", "sourceaudiopath", "audio"], sourceaudiopath: ["sourceaudiopath", "sourceaudio", "audio"], targetaudio: ["targetaudio", "targetaudiopath", "referenceaudio", "refaudio"], targetaudiopath: ["targetaudiopath", "targetaudio", "referenceaudio", "refaudio"], inputimage: ["inputimage", "image", "sourceimage"], input: ["input", "audio", "image", "video"]
  };
  for (const alias of aliases[n] ?? []) { const value = Object.entries(inputs).find(([key]) => normal(key) === alias)?.[1]; if (value !== undefined) return value; }
  if (n.includes("random") && n.includes("seed")) return inputs.randomize_seed ?? inputs.use_random_seed ?? inputs.random_seed_checkbox;
  if (n.includes("seed")) return inputs.seed ?? inputs.random_seed;
  if (n.includes("duration")) return inputs.duration ?? inputs.audio_duration;
  if (n.includes("height")) return inputs.height;
  if (n.includes("width")) return inputs.width;
  if (n.includes("language") || n === "lang") return inputs.language ?? inputs.vocal_language;
  if (n.includes("speaker") || n.includes("voiceid")) return inputs.speaker;
  if (n.includes("instruct")) return inputs.instruct;
  if (n.includes("steps") || n.includes("inferstep")) return inputs.steps ?? inputs.inference_steps ?? inputs.diffusion_steps;
  if (n.includes("cfg") || n.includes("guidance")) return inputs.cfg_strength ?? inputs.guidance_scale ?? inputs.inference_cfg_rate;
  if (n.includes("audioformat") || n === "format") return inputs.file_type ?? inputs.audio_format;
  if (n.includes("instrumental")) return inputs.instrumental ?? false;
  return undefined;
}
function score(logical: LogicalId, endpoint: string, spec: EndpointInfo, inputs: Record<string, unknown>) { const text = normal(`${endpoint} ${spec.fn ?? ""} ${spec.description ?? ""}`); const words: Record<LogicalId, string[]> = { speechToText: ["transcrib", "whisper", "asr", "speech", "stt"], music: ["music", "song", "generate", "create", "infer"], image: ["image", "txt2img", "text2image", "generate", "create"], video: ["video", "i2v", "image2video", "generate", "create", "infer"], voiceClone: ["clone", "voice", "tts", "generate"], voicePreset: ["custom", "tts", "voice", "generate"], voiceSwap: ["convert", "voice", "rvc", "seed", "singing"], vocalSeparation: ["separat", "stem", "demucs", "vocal"] }; let result = words[logical].reduce((n, word) => n + (text.includes(word) ? 12 : 0), 0); for (const p of spec.parameters ?? []) { const component = normal(`${p.component ?? ""} ${p.type ?? ""}`); const value = inputFor(p.parameter_name ?? p.label ?? "", inputs); const hidden = component.includes("state") || component.includes("event") || component.includes("button"); if (value !== undefined || p.default !== undefined || p.optional || p.parameter_has_default || hidden) result += 7; else result -= 35; if (logical === "image" && component.includes("image")) result += 18; if (logical === "video" && (component.includes("image") || component.includes("video"))) result += 18; if (logical === "speechToText" && component.includes("audio")) result += 18; } for (const output of spec.returns ?? []) { const out = normal(JSON.stringify(output)); if (logical === "image" && out.includes("image")) result += 25; if (logical === "video" && out.includes("video")) result += 25; if (["music", "voiceClone", "voicePreset", "voiceSwap", "vocalSeparation"].includes(logical) && out.includes("audio")) result += 25; if (logical === "speechToText" && (out.includes("text") || out.includes("string"))) result += 20; } return result; }

async function api(space: string, force = false, onStatus?: (message: string) => void) { const cached = apiCache.get(space); if (!force && cached && cached.expires > Date.now()) return cached.info; const client = await withTimeout(connectFreeSpace(space, onStatus), CONNECT_TIMEOUT, `Could not connect to ${space}.`); if (!client.view_api) throw new Error(`Live API metadata is unavailable for ${space}.`); const info = await withTimeout(client.view_api(), API_TIMEOUT, `The live API for ${space} did not respond.`); if (!Object.keys(endpoints(info)).length) throw new Error(`${space} exposed no callable endpoints.`); apiCache.set(space, { info, expires: Date.now() + CACHE_TTL }); return info; }
async function resolve(logical: LogicalId, space: string, inputs: Inputs, preferred: string | undefined, force: boolean, onStatus?: (message: string) => void) { const client = await withTimeout(connectFreeSpace(space, onStatus), CONNECT_TIMEOUT, `Could not connect to ${space}.`); const map = endpoints(await api(space, force, onStatus)); const record = Array.isArray(inputs) ? {} : inputs as Record<string, unknown>; if (preferred && map[preferred] && score(logical, preferred, map[preferred], record) >= 0) return { client, endpoint: preferred, spec: map[preferred] }; const ranked = Object.entries(map).map(([endpoint, spec]) => ({ endpoint, spec, score: score(logical, endpoint, spec, record) })).sort((a, b) => b.score - a.score); const best = ranked[0]; if (!best || best.score < 0) throw new Error(`No compatible endpoint for ${logical} is currently exposed by ${space}.`); return { client, endpoint: best.endpoint, spec: best.spec }; }
async function normalize(value: unknown): Promise<unknown> { if (typeof Blob !== "undefined" && value instanceof Blob) return handle_file(value); if (Array.isArray(value)) return Promise.all(value.map(normalize)); if (value && typeof value === "object") return Object.fromEntries(await Promise.all(Object.entries(value as Record<string, unknown>).map(async ([key, item]) => [key, await normalize(item)] as const))); return value; }
function payload(logical: LogicalId, spec: EndpointInfo, inputs: Inputs) { if (Array.isArray(inputs)) return inputs; const record = inputs as Record<string, unknown>; return (spec.parameters ?? []).map((p) => { const value = inputFor(p.parameter_name ?? p.label ?? "", record); if (value !== undefined) return value; if (p.default !== undefined) return p.default; if (p.optional || p.parameter_has_default || normal(p.component).includes("state")) return null; throw new Error(`Required live input missing: ${p.parameter_name ?? p.label ?? "unknown"}`); }); }
function artifact(value: unknown): string | null { if (typeof Blob !== "undefined" && value instanceof Blob) return URL.createObjectURL(value); if (typeof value === "string") { const s = value.trim(); if (/^(https?:|blob:|data:|\/gradio_api\/file=|\/file=|file=|\/tmp\/|\/home\/|\/data\/)/.test(s)) return s; try { return s.startsWith("{") || s.startsWith("[") ? artifact(JSON.parse(s)) : null; } catch { return null; } } if (!value || typeof value !== "object") return null; if (Array.isArray(value)) { for (const item of value) { const found = artifact(item); if (found) return found; } return null; } const r = value as Record<string, unknown>; for (const key of ["url", "path", "blob", "file", "audio", "image", "video", "data", "value", "audio_url", "image_url", "video_url"]) { const found = artifact(r[key]); if (found) return found; } return null; }
export function outputUrl(value: unknown) { return artifact(value); }
export function firstOutput(value: unknown): unknown { if (value && typeof value === "object" && "data" in value) return (value as Record<string, unknown>).data; return value; }
function textResult(value: unknown): string | null { if (typeof value === "string" && value.trim()) return value.trim(); if (Array.isArray(value)) for (const item of value) { const found = textResult(item); if (found) return found; } if (value && typeof value === "object") { const r = value as Record<string, unknown>; for (const key of ["text", "generated_text", "transcript", "transcription", "content", "value", "data"]) { const found = textResult(r[key]); if (found) return found; } } return null; }
function usable(logical: LogicalId, result: unknown) { const value = firstOutput(result); return logical === "speechToText" ? Boolean(textResult(value)) : Boolean(artifact(value)); }
async function execute(client: ClientLike, endpoint: string, spec: EndpointInfo, logical: LogicalId, inputs: Inputs) { const data = await normalize(payload(logical, spec, inputs)); try { return await withTimeout(client.predict(endpoint, data), JOB_TIMEOUT, "The live free generation job timed out."); } catch (directError) { let latest: unknown = null; try { const job = client.submit(endpoint, data); for await (const message of job) { if (message.type === "status" && message.message) console.debug(`[Little Red's Big Studio] ${message.message}`); if (message.type === "data") latest = message.data; } } catch (queueError) { throw new Error(`Direct and queued generation failed: ${directError instanceof Error ? directError.message : String(directError)}; ${queueError instanceof Error ? queueError.message : String(queueError)}`); } if (latest == null) throw new Error("The live engine completed without returning a result."); return latest; } }
async function runRoute(logical: LogicalId, space: string, inputs: Inputs, onStatus?: (message: string) => void, preferred?: string) { const current = state(logical, space); if (current.nextRetryAt > Date.now()) throw new Error(`${space} is cooling down after a recent failure.`); let last: unknown; for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt++) { try { onStatus?.(attempt ? "Retrying the live engine…" : `Connecting to ${space}…`); const resolved = await resolve(logical, space, inputs, preferred, attempt > 0, onStatus); const result = await execute(resolved.client, resolved.endpoint, resolved.spec, logical, inputs); if (!usable(logical, result)) throw new Error("The live engine returned no usable output."); success(logical, space); return logical === "speechToText" ? textResult(firstOutput(result)) ?? result : firstOutput(result); } catch (error) { last = error; failure(logical, space, error); onStatus?.("That free engine failed; automatically trying the next best available engine…"); } } throw last instanceof Error ? last : new Error(`Free engine ${space} failed.`); }
async function collect(logical: LogicalId, inputs: Inputs, onStatus?: (message: string) => void, preferred?: string) { const now = Date.now(); const candidates = spaceNames(logical).filter((r) => state(logical, r.id).nextRetryAt <= now).sort((a, b) => (b.priority - state(logical, b.id).failures * 15) - (a.priority - state(logical, a.id).failures * 15)); if (!candidates.length) throw new Error(`No healthy free engine is available for ${logical} right now.`); let last: unknown; for (const route of candidates) { try { return await runRoute(logical, route.id, inputs, onStatus, preferred); } catch (error) { last = error; } } throw last instanceof Error ? last : new Error(`No free engine could complete ${logical}.`); }
function logicalFor(space: string): LogicalId | "" { if (space in FREE_SPACE_IDS) return space as LogicalId; return (Object.keys(FREE_SPACE_IDS) as LogicalId[]).find((logical) => spaceNames(logical).some((r) => r.id === space)) ?? ""; }
export function getFreeRuntimeHealth() { return Object.fromEntries(health.entries()); }
export function resetFreeRuntimeHealth() { health.clear(); clients.clear(); apiCache.clear(); }
export async function probeFreeRoute(logicalId: string) { if (!(logicalId in FREE_SPACE_IDS)) return false; for (const route of spaceNames(logicalId as LogicalId)) { try { await api(route.id, true); success(logicalId as LogicalId, route.id); return true; } catch (error) { failure(logicalId as LogicalId, route.id, error); } } return false; }
export async function runGradio(space: string, apiName: string, inputs: Inputs, onStatus?: (message: string) => void) { const logical = logicalFor(space); if (!logical) throw new Error(`Unknown free generation service: ${space}`); return collect(logical, inputs, onStatus, apiName || undefined); }
export async function runGradioAll(space: string, apiName: string, inputs: Inputs, onStatus?: (message: string) => void) { const result = await runGradio(space, apiName, inputs, onStatus); return Array.isArray(result) ? result : [result]; }
