import type { PluginRow } from "./plugins.server";

/**
 * Curated free/open models that can be reached from the Studio without Colab,
 * a desktop computer, paid APIs, or user-supplied provider keys.
 * Heavy inference is routed to public browser Spaces; lightweight fallbacks
 * may run locally in the Android browser.
 */
export const OPEN_MODEL_CATALOG: PluginRow[] = [
  {
    id: "open-qwen3-tts",
    slug: "qwen3-tts-open",
    name: "Qwen3-TTS",
    capability: "voice",
    provider: "open-source",
    model_ref: "Qwen3-TTS",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 9,
    weekly_score: 10,
    enabled: true,
    notes: "Voice design, cloning and natural speech through the official free public Space.",
    runtime: "browser",
    project_url: "https://huggingface.co/spaces/Qwen/Qwen3-TTS",
  },
  {
    id: "open-moss-tts",
    slug: "moss-tts-open",
    name: "MOSS-TTS v1.5",
    capability: "voice",
    provider: "open-source",
    model_ref: "MOSS-TTS v1.5",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 8,
    weekly_score: 10,
    enabled: true,
    notes: "Zero-shot voice cloning and multilingual long-form speech fallback.",
    runtime: "browser",
    project_url: "https://huggingface.co/spaces/OpenMOSS-Team/MOSS-TTS-v1.5",
  },
  {
    id: "open-chatterbox",
    slug: "chatterbox-open",
    name: "Chatterbox Multilingual",
    capability: "voice",
    provider: "open-source",
    model_ref: "Chatterbox Multilingual",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 8,
    weekly_score: 10,
    enabled: true,
    notes: "High-quality multilingual TTS and voice-cloning fallback.",
    runtime: "browser",
    project_url: "https://huggingface.co/spaces/ResembleAI/Chatterbox-Multilingual-TTS",
  },
  {
    id: "open-seed-vc",
    slug: "seed-vc-open",
    name: "Seed-VC",
    capability: "voice",
    provider: "open-source",
    model_ref: "Seed-VC",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 8,
    weekly_score: 10,
    enabled: true,
    notes: "Zero-shot speech and singing voice conversion through a public free Space.",
    runtime: "browser",
    project_url: "https://huggingface.co/spaces/Plachta/Seed-VC",
  },
  {
    id: "open-rvc",
    slug: "rvc-open",
    name: "RVC / Applio",
    capability: "voice",
    provider: "open-source",
    model_ref: "Retrieval-based Voice Conversion",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 8,
    weekly_score: 10,
    enabled: true,
    notes: "Open voice-conversion stack for voice conversion, cloning and cover workflows.",
    runtime: "browser",
    project_url: "https://huggingface.co/spaces/IAHispano/ApplioX",
  },
  {
    id: "open-demucs",
    slug: "demucs-open",
    name: "Demucs",
    capability: "stems",
    provider: "open-source",
    model_ref: "htdemucs",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 8,
    weekly_score: 10,
    enabled: true,
    notes: "High-quality open music source separation.",
    runtime: "browser",
    project_url: "https://github.com/facebookresearch/demucs",
  },
  {
    id: "open-wan-22",
    slug: "wan-22-open",
    name: "Wan 2.2",
    capability: "video",
    provider: "open-source",
    model_ref: "Wan2.2",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 8,
    weekly_score: 10,
    enabled: true,
    notes: "High-quality open image-to-video route through a public free ZeroGPU Space.",
    runtime: "browser",
    project_url: "https://huggingface.co/spaces/zerogpu-aoti/wan2-2-fp8da-aoti-faster",
  },
  {
    id: "open-ltx-23",
    slug: "ltx-23-open",
    name: "LTX 2.3",
    capability: "video",
    provider: "open-source",
    model_ref: "LTX-2.3",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 9,
    weekly_score: 10,
    enabled: true,
    notes: "Open video generation with synchronized audio through a free public Space.",
    runtime: "browser",
    project_url: "https://huggingface.co/spaces/Lightricks/LTX-2-3",
  },
  {
    id: "open-ace-step",
    slug: "ace-step-open",
    name: "ACE-Step 1.5",
    capability: "music",
    provider: "open-source",
    model_ref: "ACE-Step 1.5",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 9,
    weekly_score: 10,
    enabled: true,
    notes: "Powerful open music generation, editing, cover and vocal-to-BGM engine.",
    runtime: "browser",
    project_url: "https://huggingface.co/spaces/ACE-Step/Ace-Step-v1.5",
  },
  {
    id: "open-diffrhythm-2",
    slug: "diffrhythm-2-open",
    name: "DiffRhythm 2",
    capability: "music",
    provider: "open-source",
    model_ref: "DiffRhythm 2",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 9,
    weekly_score: 10,
    enabled: true,
    notes: "High-fidelity controllable full-song generation through a public ZeroGPU Space.",
    runtime: "browser",
    project_url: "https://huggingface.co/spaces/ASLP-lab/DiffRhythm2",
  },
  {
    id: "open-qwen-image",
    slug: "qwen-image-open",
    name: "Qwen Image",
    capability: "image",
    provider: "open-source",
    model_ref: "Qwen-Image",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 9,
    weekly_score: 10,
    enabled: true,
    notes: "Official Qwen image-generation route running on free public ZeroGPU.",
    runtime: "browser",
    project_url: "https://huggingface.co/spaces/Qwen/Qwen-Image",
  },
  {
    id: "open-qwen-image-edit",
    slug: "qwen-image-edit-open",
    name: "Qwen Image Edit",
    capability: "image",
    provider: "open-source",
    model_ref: "Qwen-Image-Edit",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 8,
    weekly_score: 10,
    enabled: true,
    notes: "Natural-language image editing and transformation through a public free Space.",
    runtime: "browser",
    project_url: "https://huggingface.co/spaces/Qwen/Qwen-Image-Edit",
  },
  {
    id: "open-z-image",
    slug: "z-image-open",
    name: "Z Image Turbo",
    capability: "image",
    provider: "open-source",
    model_ref: "Z Image Turbo",
    secret_name: null,
    is_free: true,
    quality: 9,
    speed: 10,
    weekly_score: 9,
    enabled: true,
    notes: "Fast open image-generation fallback.",
    runtime: "browser",
    project_url: "https://huggingface.co/spaces/hf-applications/Z-Image-Turbo",
  },
  {
    id: "open-sdxl",
    slug: "sdxl-open",
    name: "Stable Diffusion XL",
    capability: "image",
    provider: "open-source",
    model_ref: "stabilityai/stable-diffusion-xl-base-1.0",
    secret_name: null,
    is_free: true,
    quality: 9,
    speed: 7,
    weekly_score: 9,
    enabled: true,
    notes: "Mature open image-generation fallback; older but still useful when stronger routes fail.",
    runtime: "browser",
    project_url: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0",
  },
  {
    id: "open-whisper",
    slug: "whisper-open",
    name: "Whisper",
    capability: "text",
    provider: "open-source",
    model_ref: "Whisper",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 8,
    weekly_score: 10,
    enabled: true,
    notes: "Open speech recognition for transcription and captions.",
    runtime: "browser",
    project_url: "https://huggingface.co/spaces/hf-audio/whisper-large-v3-turbo",
  },
  {
    id: "open-qwen3-asr",
    slug: "qwen3-asr-open",
    name: "Qwen3-ASR",
    capability: "text",
    provider: "open-source",
    model_ref: "Qwen3-ASR",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 9,
    weekly_score: 10,
    enabled: true,
    notes: "Modern speech recognition and transcription fallback.",
    runtime: "browser",
    project_url: "https://huggingface.co/spaces/Qwen/Qwen3-ASR",
  },
];