import type { PluginRow } from "./plugins.server";

/**
 * Curated starting catalog for Little Red's provider-free architecture.
 *
 * These entries intentionally contain no API credentials or commercial
 * inference providers. Heavy models are executed through free local/Colab
 * runners; the catalog only describes the open model and its public project.
 */
export const OPEN_MODEL_CATALOG: PluginRow[] = [
  {
    id: "open-rvc",
    slug: "rvc-open",
    name: "RVC",
    capability: "voice",
    provider: "open-source",
    model_ref: "Retrieval-based Voice Conversion",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 8,
    weekly_score: 10,
    enabled: true,
    notes: "Open voice-conversion stack; ideal for free voice conversion and cloning workflows.",
    runtime: "colab",
    project_url: "https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI",
  },
  {
    id: "open-demucs",
    slug: "demucs-open",
    name: "Demucs",
    capability: "stems",
    provider: "open-source",
    model_ref: "htdemucs",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 8,
    weekly_score: 10,
    enabled: true,
    notes: "High-quality open music source separation.",
    runtime: "local",
    project_url: "https://github.com/facebookresearch/demucs",
  },
  {
    id: "open-wan",
    slug: "wan-open",
    name: "Wan",
    capability: "video",
    provider: "open-source",
    model_ref: "Wan2.1",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 5,
    weekly_score: 10,
    enabled: true,
    notes: "Open video-generation family; best suited to free GPU/Colab execution.",
    runtime: "colab",
    project_url: "https://github.com/Wan-Video/Wan2.1",
  },
  {
    id: "open-ltx-video",
    slug: "ltx-video-open",
    name: "LTX-Video",
    capability: "video",
    provider: "open-source",
    model_ref: "LTX-Video",
    secret_name: null,
    is_free: true,
    quality: 9,
    speed: 7,
    weekly_score: 9,
    enabled: true,
    notes: "Open video generation with a useful speed/quality tradeoff.",
    runtime: "colab",
    project_url: "https://github.com/Lightricks/LTX-Video",
  },
  {
    id: "open-kokoro",
    slug: "kokoro-open",
    name: "Kokoro TTS",
    capability: "voice",
    provider: "open-source",
    model_ref: "Kokoro-82M",
    secret_name: null,
    is_free: true,
    quality: 9,
    speed: 10,
    weekly_score: 9,
    enabled: true,
    notes: "Compact open text-to-speech model suitable for practical local execution.",
    runtime: "local",
    project_url: "https://huggingface.co/hexgrad/Kokoro-82M",
  },
  {
    id: "open-whisper",
    slug: "whisper-open",
    name: "Whisper",
    capability: "text",
    provider: "open-source",
    model_ref: "Whisper",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 8,
    weekly_score: 10,
    enabled: true,
    notes: "Open speech recognition for transcription, captions and voice workflows.",
    runtime: "local",
    project_url: "https://github.com/openai/whisper",
  },
];
