import type { PluginRow } from "./plugins.server";

/**
 * Curated catalog of open/open-weight models with no API credentials.
 * Heavy jobs are routed to public browser Spaces or free GPU workspaces
 * such as Kaggle/Lightning; Colab is not required.
 */
export const OPEN_MODEL_CATALOG: PluginRow[] = [
  {
    id: "open-rvc",
    slug: "rvc-open",
    name: "RVC / Applio",
    capability: "voice",
    provider: "open-source",
    model_ref: "Retrieval-based Voice Conversion",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 8,
    weekly_score: 10,
    enabled: true,
    notes: "Open voice-conversion stack for voice conversion, cloning and cover workflows.",
    runtime: "browser",
    project_url: "https://huggingface.co/spaces/IAHispano/ApplioX",
  },
  {
    id: "open-demucs",
    slug: "demucs-open",
    name: "Demucs",
    capability: "stems",
    provider: "open-source",
    model_ref: "htdemucs",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 8,
    weekly_score: 10,
    enabled: true,
    notes: "High-quality open music source separation.",
    runtime: "browser",
    project_url: "https://github.com/facebookresearch/demucs",
  },
  {
    id: "open-wan",
    slug: "wan-open",
    name: "Wan 2.1",
    capability: "video",
    provider: "open-source",
    model_ref: "Wan2.1",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 5,
    weekly_score: 10,
    enabled: true,
    notes: "Open video generation; use a public browser Space or free GPU workspace.",
    runtime: "browser",
    project_url: "https://github.com/Wan-Video/Wan2.1",
  },
  {
    id: "open-ltx-video",
    slug: "ltx-video-open",
    name: "LTX-Video",
    capability: "video",
    provider: "open-source",
    model_ref: "LTX-Video",
    secret_name: null,
    is_free: true,
    quality: 9,
    speed: 7,
    weekly_score: 9,
    enabled: true,
    notes: "Open video generation with a useful speed/quality tradeoff.",
    runtime: "browser",
    project_url: "https://github.com/Lightricks/LTX-Video",
  },
  {
    id: "open-kokoro",
    slug: "kokoro-open",
    name: "Kokoro TTS",
    capability: "voice",
    provider: "open-source",
    model_ref: "Kokoro-82M",
    secret_name: null,
    is_free: true,
    quality: 9,
    speed: 10,
    weekly_score: 9,
    enabled: true,
    notes: "Compact open TTS model suitable for local/browser execution.",
    runtime: "local",
    project_url: "https://huggingface.co/hexgrad/Kokoro-82M",
  },
  {
    id: "open-whisper",
    slug: "whisper-open",
    name: "Whisper",
    capability: "text",
    provider: "open-source",
    model_ref: "Whisper",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 8,
    weekly_score: 10,
    enabled: true,
    notes: "Open speech recognition for transcription and captions.",
    runtime: "local",
    project_url: "https://github.com/openai/whisper",
  },
  {
    id: "open-laguna-s21",
    slug: "laguna-s21-open",
    name: "Laguna S 2.1",
    capability: "text",
    provider: "open-source",
    model_ref: "poolside/Laguna-S-2.1",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 7,
    weekly_score: 10,
    enabled: true,
    notes:
      "Open long-context reasoning and coding model. Heavy inference uses a free GPU workspace; smaller quantized builds can run locally on capable hardware.",
    runtime: "kaggle",
    project_url: "https://huggingface.co/poolside/Laguna-S-2.1",
  },
  {
    id: "open-ace-step",
    slug: "ace-step-open",
    name: "ACE-Step 1.5",
    capability: "music",
    provider: "open-source",
    model_ref: "ACE-Step 1.5",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 9,
    weekly_score: 10,
    enabled: true,
    notes:
      "Powerful open music generation, editing, cover and vocal-to-BGM engine. Its public Hugging Face Space provides the easiest no-key browser path.",
    runtime: "browser",
    project_url: "https://huggingface.co/spaces/ACE-Step/Ace-Step-v1.5",
  },
  {
    id: "open-diffrhythm-2",
    slug: "diffrhythm-2-open",
    name: "DiffRhythm 2",
    capability: "music",
    provider: "open-source",
    model_ref: "DiffRhythm 2",
    secret_name: null,
    is_free: true,
    quality: 10,
    speed: 9,
    weekly_score: 10,
    enabled: true,
    notes:
      "High-fidelity controllable full-song generation with strong lyric alignment; use a free GPU runner for heavy inference.",
    runtime: "kaggle",
    project_url: "https://huggingface.co/ASLP-lab/DiffRhythm2",
  },
  {
    id: "open-heartmula",
    slug: "heartmula-open",
    name: "HeartMuLa OSS 3B",
    capability: "music",
    provider: "open-source",
    model_ref: "HeartMuLa OSS 3B",
    secret_name: null,
    is_free: true,
    quality: 9,
    speed: 7,
    weekly_score: 9,
    enabled: true,
    notes:
      "Open long-form song generation option; use a free GPU runner when the phone cannot handle the model.",
    runtime: "kaggle",
    project_url: "https://huggingface.co/models?search=HeartMuLa",
  },
  {
    id: "open-yue",
    slug: "yue-open",
    name: "YuE",
    capability: "music",
    provider: "open-source",
    model_ref: "YuE",
    secret_name: null,
    is_free: true,
    quality: 9,
    speed: 6,
    weekly_score: 9,
    enabled: true,
    notes:
      "Open long-form lyrics-to-song generation and style-transfer research stack; heavy runner recommended.",
    runtime: "kaggle",
    project_url: "https://github.com/multimodal-art-projection/YuE",
  },
  {
    id: "open-sdxl",
    slug: "sdxl-open",
    name: "Stable Diffusion XL",
    capability: "image",
    provider: "open-source",
    model_ref: "stabilityai/stable-diffusion-xl-base-1.0",
    secret_name: null,
    is_free: true,
    quality: 9,
    speed: 7,
    weekly_score: 9,
    enabled: true,
    notes: "Widely supported open image-generation model; use a public browser demo or local runtime.",
    runtime: "browser",
    project_url: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0",
  },
  {
    id: "open-musicgen",
    slug: "musicgen-open",
    name: "MusicGen",
    capability: "music",
    provider: "open-source",
    model_ref: "facebook/musicgen-small",
    secret_name: null,
    is_free: true,
    quality: 8,
    speed: 7,
    weekly_score: 8,
    enabled: true,
    notes: "Open music generation model with an in-browser implementation available.",
    runtime: "browser",
    project_url: "https://huggingface.co/spaces/Xenova/musicgen-web",
  },
];
